# Makefile for SBLIM (/etc/init.d) Service Instrumentation (Pegasus flavor)

include ../setting.cmpi

install:
	cimmofl -I. -nroot/cimv2 Linux_Service.mof
	cimmofl -I. -nroot/PG_InterOp Linux_ServiceRegistration.mof






